test-job1:
  image: centos:7
  stage: test
  script:
    - yum -y update && yum install -y gcc gcc-c++ python3 python3-devel make automake git libtool libtool-ltdl-devel openmpi openmpi-devel zlib-devel wget
    - mkdir -p build && ./autogen.sh && cd build 
    - ../configure --prefix=$PWD/../install --disable-mpi && make -j $(nproc) install
    - ../install/bin/sst-test-core
